/* Automatically generated by wasm2c */
#ifndef MYLIB_WASM_H_GENERATED_
#define MYLIB_WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi__snapshot__preview1;
extern wasm_rt_funcref_table_t* w2c_env_0x5F_indirect_function_table(struct w2c_env*);
extern wasm_rt_memory_t* w2c_env_memory(struct w2c_env*);

typedef struct w2c_mylib {
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  /* import: 'env' '__indirect_function_table' */
  wasm_rt_funcref_table_t *w2c_env_0x5F_indirect_function_table;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *w2c_env_memory;
  u32 w2c_g0; // malloc uses this so might track last malloced location?
  u32 w2c_SECRET_NUM; // this stores a ptr to the global var section where this is located
  u32 w2c_CONST_SECRET_NUM2;
  u32 w2c_CONST_SECRET_NUM3;
  u32 w2c_CONST_SECRET_NUM4;
  u32 w2c_0x5F_heap_base; // heap base?
  u32 w2c_errno;
  u32 w2c_0x5F_progname;
  u32 w2c_0x5F_progname_full;
  u32 w2c_0x5F_libc;
  u32 w2c_0x5F_hwcap;
  u32 w2c_program_invocation_short_name;
  u32 w2c_program_invocation_name;
  u32 w2c_0x5F_stdin_used; 
  u32 w2c_0x5F_stdout_used; // stop printing after once
  u32 w2c_0x5F_stderr_used;
  u32 w2c_0x5F_stdout_FILE;
  u32 w2c_0x5F_stderr_FILE;
  u32 w2c_stderr;
  u32 w2c_stdout;
  u32 w2c_0x5F_dso_handle;
  u32 w2c_0x5F_data_end; // 
  u32 w2c_0x5F_global_base;
  u32 w2c_0x5F_memory_base;
  u32 w2c_0x5F_table_base;
} w2c_mylib;

void wasm2c_mylib_instantiate(w2c_mylib*, struct w2c_env*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_mylib_free(w2c_mylib*);
wasm_rt_func_type_t wasm2c_mylib_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi_snapshot_preview1' 'args_get' */
u32 w2c_wasi__snapshot__preview1_args_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
u32 w2c_wasi__snapshot__preview1_args_sizes_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
u32 w2c_wasi__snapshot__preview1_fd_fdstat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_seek' */
u32 w2c_wasi__snapshot__preview1_fd_seek(struct w2c_wasi__snapshot__preview1*, u32, u64, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);

extern const u32 wasm2c_mylib_min_env_0x5F_indirect_function_table;
extern const u32 wasm2c_mylib_max_env_0x5F_indirect_function_table;
extern const u64 wasm2c_mylib_min_env_memory;
extern const u64 wasm2c_mylib_max_env_memory;
extern const u8 wasm2c_mylib_is64_env_memory;

/* export: '__wasm_call_ctors' */
void w2c_mylib_0x5F_wasm_call_ctors(w2c_mylib*);

/* export: '_start' */
void w2c_mylib_0x5Fstart(w2c_mylib*);

/* export: '__original_main' */
u32 w2c_mylib_0x5F_original_main(w2c_mylib*);

/* export: '__wasm_call_dtors' */
void w2c_mylib_0x5F_wasm_call_dtors(w2c_mylib*);

/* export: '__main_argc_argv' */
u32 w2c_mylib_0x5F_main_argc_argv(w2c_mylib*, u32, u32);

/* export: 'abort' */
void w2c_mylib_abort(w2c_mylib*);

/* export: 'hello' */
void w2c_mylib_hello(w2c_mylib*);

/* export: 'puts' */
u32 w2c_mylib_puts(w2c_mylib*, u32);

/* export: 'add' */
u32 w2c_mylib_add(w2c_mylib*, u32, u32);

/* export: 'leak_secret_num' */
u32 w2c_mylib_leak_secret_num(w2c_mylib*);

/* export: 'SECRET_NUM' */
u32* w2c_mylib_SECRET_NUM(w2c_mylib* instance);

/* export: 'leak_const_secret_num' */
u32 w2c_mylib_leak_const_secret_num(w2c_mylib*);

/* export: 'naive_concat' */
u32 w2c_mylib_naive_concat(w2c_mylib*, u32, u32);

/* export: 'strlen' */
u32 w2c_mylib_strlen(w2c_mylib*, u32);

/* export: 'malloc' */
u32 w2c_mylib_malloc(w2c_mylib*, u32);

/* export: 'memcpy' */
u32 w2c_mylib_memcpy(w2c_mylib*, u32, u32, u32);

/* export: 'm' */
u32 w2c_mylib_m(w2c_mylib*);

/* export: 'printf' */
u32 w2c_mylib_printf(w2c_mylib*, u32, u32);

/* export: 'l' */
u32 w2c_mylib_l(w2c_mylib*);

/* export: 'h' */
u32 w2c_mylib_h(w2c_mylib*);

/* export: 'f' */
u32 w2c_mylib_f(w2c_mylib*);

/* export: 'e' */
u32 w2c_mylib_e(w2c_mylib*);

/* export: 'd' */
u32 w2c_mylib_d(w2c_mylib*);

/* export: 'c' */
u32 w2c_mylib_c(w2c_mylib*);

/* export: 'b' */
u32 w2c_mylib_b(w2c_mylib*);

/* export: 'a' */
u32 w2c_mylib_a(w2c_mylib*);

/* export: 'CONST_SECRET_NUM2' */
u32* w2c_mylib_CONST_SECRET_NUM2(w2c_mylib* instance);

/* export: 'CONST_SECRET_NUM3' */
u32* w2c_mylib_CONST_SECRET_NUM3(w2c_mylib* instance);

/* export: 'CONST_SECRET_NUM4' */
u32* w2c_mylib_CONST_SECRET_NUM4(w2c_mylib* instance);

/* export: 'sbrk' */
u32 w2c_mylib_sbrk(w2c_mylib*, u32);

/* export: '__heap_base' */
u32* w2c_mylib_0x5F_heap_base(w2c_mylib* instance);

/* export: 'errno' */
u32* w2c_mylib_errno(w2c_mylib* instance);

/* export: 'free' */
void w2c_mylib_free(w2c_mylib*, u32);

/* export: 'calloc' */
u32 w2c_mylib_calloc(w2c_mylib*, u32, u32);

/* export: 'memset' */
u32 w2c_mylib_memset(w2c_mylib*, u32, u32, u32);

/* export: 'realloc' */
u32 w2c_mylib_realloc(w2c_mylib*, u32, u32);

/* export: 'posix_memalign' */
u32 w2c_mylib_posix_memalign(w2c_mylib*, u32, u32, u32);

/* export: 'aligned_alloc' */
u32 w2c_mylib_aligned_alloc(w2c_mylib*, u32, u32);

/* export: 'malloc_usable_size' */
u32 w2c_mylib_malloc_usable_size(w2c_mylib*, u32);

/* export: '__lseek' */
u64 w2c_mylib_0x5F_lseek(w2c_mylib*, u32, u64, u32);

/* export: 'lseek' */
u64 w2c_mylib_lseek(w2c_mylib*, u32, u64, u32);

/* export: 'close' */
u32 w2c_mylib_close(w2c_mylib*, u32);

/* export: 'writev' */
u32 w2c_mylib_writev(w2c_mylib*, u32, u32, u32);

/* export: '_Exit' */
void w2c_mylib_0x5FExit(w2c_mylib*, u32);

/* export: '_exit' */
void w2c_mylib_0x5Fexit(w2c_mylib*, u32);

/* export: '__main_void' */
u32 w2c_mylib_0x5F_main_void(w2c_mylib*);

/* export: '__isatty' */
u32 w2c_mylib_0x5F_isatty(w2c_mylib*, u32);

/* export: 'isatty' */
u32 w2c_mylib_isatty(w2c_mylib*, u32);

/* export: '__strerror_l' */
u32 w2c_mylib_0x5F_strerror_l(w2c_mylib*, u32, u32);

/* export: 'strerror' */
u32 w2c_mylib_strerror(w2c_mylib*, u32);

/* export: 'strerror_l' */
u32 w2c_mylib_strerror_l(w2c_mylib*, u32, u32);

/* export: '__funcs_on_exit' */
void w2c_mylib_0x5F_funcs_on_exit(w2c_mylib*);

/* export: '__stdio_exit' */
void w2c_mylib_0x5F_stdio_exit(w2c_mylib*);

/* export: 'exit' */
void w2c_mylib_exit(w2c_mylib*, u32);

/* export: '__progname' */
u32* w2c_mylib_0x5F_progname(w2c_mylib* instance);

/* export: '__progname_full' */
u32* w2c_mylib_0x5F_progname_full(w2c_mylib* instance);

/* export: '__libc' */
u32* w2c_mylib_0x5F_libc(w2c_mylib* instance);

/* export: '__hwcap' */
u32* w2c_mylib_0x5F_hwcap(w2c_mylib* instance);

/* export: 'program_invocation_short_name' */
u32* w2c_mylib_program_invocation_short_name(w2c_mylib* instance);

/* export: 'program_invocation_name' */
u32* w2c_mylib_program_invocation_name(w2c_mylib* instance);

/* export: '__overflow' */
u32 w2c_mylib_0x5F_overflow(w2c_mylib*, u32, u32);

/* export: '__stdio_close' */
u32 w2c_mylib_0x5F_stdio_close(w2c_mylib*, u32);

/* export: '__stdin_used' */
u32* w2c_mylib_0x5F_stdin_used(w2c_mylib* instance);

/* export: '__stdout_used' */
u32* w2c_mylib_0x5F_stdout_used(w2c_mylib* instance);

/* export: '__stderr_used' */
u32* w2c_mylib_0x5F_stderr_used(w2c_mylib* instance);

/* export: '__stdio_exit_needed' */
void w2c_mylib_0x5F_stdio_exit_needed(w2c_mylib*);

/* export: '__stdio_seek' */
u64 w2c_mylib_0x5F_stdio_seek(w2c_mylib*, u32, u64, u32);

/* export: '__stdio_write' */
u32 w2c_mylib_0x5F_stdio_write(w2c_mylib*, u32, u32, u32);

/* export: '__stdout_write' */
u32 w2c_mylib_0x5F_stdout_write(w2c_mylib*, u32, u32, u32);

/* export: '__towrite' */
u32 w2c_mylib_0x5F_towrite(w2c_mylib*, u32);

/* export: '__towrite_needs_stdio_exit' */
void w2c_mylib_0x5F_towrite_needs_stdio_exit(w2c_mylib*);

/* export: 'fputs' */
u32 w2c_mylib_fputs(w2c_mylib*, u32, u32);

/* export: 'fputs_unlocked' */
u32 w2c_mylib_fputs_unlocked(w2c_mylib*, u32, u32);

/* export: '__fwritex' */
u32 w2c_mylib_0x5F_fwritex(w2c_mylib*, u32, u32, u32);

/* export: 'fwrite' */
u32 w2c_mylib_fwrite(w2c_mylib*, u32, u32, u32, u32);

/* export: 'fwrite_unlocked' */
u32 w2c_mylib_fwrite_unlocked(w2c_mylib*, u32, u32, u32, u32);

/* export: '__ofl_lock' */
u32 w2c_mylib_0x5F_ofl_lock(w2c_mylib*);

/* export: '__ofl_unlock' */
void w2c_mylib_0x5F_ofl_unlock(w2c_mylib*);

/* export: '__stdout_FILE' */
u32* w2c_mylib_0x5F_stdout_FILE(w2c_mylib* instance);

/* export: 'vfprintf' */
u32 w2c_mylib_vfprintf(w2c_mylib*, u32, u32, u32);

/* export: 'iprintf' */
u32 w2c_mylib_iprintf(w2c_mylib*, u32, u32);

/* export: '__small_printf' */
u32 w2c_mylib_0x5F_small_printf(w2c_mylib*, u32, u32);

/* export: '__stderr_FILE' */
u32* w2c_mylib_0x5F_stderr_FILE(w2c_mylib* instance);

/* export: 'stderr' */
u32* w2c_mylib_stderr(w2c_mylib* instance);

/* export: 'stdout' */
u32* w2c_mylib_stdout(w2c_mylib* instance);

/* export: '__lctrans' */
u32 w2c_mylib_0x5F_lctrans(w2c_mylib*, u32, u32);

/* export: 'strnlen' */
u32 w2c_mylib_strnlen(w2c_mylib*, u32, u32);

/* export: 'wctomb' */
u32 w2c_mylib_wctomb(w2c_mylib*, u32, u32);

/* export: 'frexp' */
f64 w2c_mylib_frexp(w2c_mylib*, f64, u32);

/* export: 'memchr' */
u32 w2c_mylib_memchr(w2c_mylib*, u32, u32, u32);

/* export: '__lctrans_impl' */
u32 w2c_mylib_0x5F_lctrans_impl(w2c_mylib*, u32, u32);

/* export: '__lctrans_cur' */
u32 w2c_mylib_0x5F_lctrans_cur(w2c_mylib*, u32);

/* export: 'wcrtomb' */
u32 w2c_mylib_wcrtomb(w2c_mylib*, u32, u32, u32);

/* export: '__dso_handle' */
u32* w2c_mylib_0x5F_dso_handle(w2c_mylib* instance);

/* export: '__data_end' */
u32* w2c_mylib_0x5F_data_end(w2c_mylib* instance);

/* export: '__global_base' */
u32* w2c_mylib_0x5F_global_base(w2c_mylib* instance);

/* export: '__memory_base' */
u32* w2c_mylib_0x5F_memory_base(w2c_mylib* instance);

/* export: '__table_base' */
u32* w2c_mylib_0x5F_table_base(w2c_mylib* instance);

#ifdef __cplusplus
}
#endif

#endif  /* MYLIB_WASM_H_GENERATED_ */
